### PR TITLE
Bug fix: outputs broken in MPI implementation

### LINKED ISSUE #359: Bug fix: outputs broken in MPI implementation
The recent changes for checking ranges [#225](https://github.com/CABLE-LSM/CABLE/issues/225) prevented all outputs in the MPI version of CABLE. This is because a new subroutine was introduced, `set_group_output_values()`, that sets the logical entries that controls which variables are output. This subroutine is not called in the MPI version resulting in all variables set to not output.

We should also add the other changes introduced in `cable_driver.F90` to the MPI implementation.

### PR DESCRIPTION
**Pull request by ccarouge**
# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Fixes #359 
Changes for checking ranges have changed how the `output%X` logical switches are set. This was not reflected in the MPI driver which meant no outputs were produced from simulations using MPI.

Fix include:
- Add call to `set_group_output_values` in cable_mpimaster.F90.
- Add call to `constant_check_range()` in cable_mpiworker.F90. This check was added during the work to check ranges in the serial version. This has no impact on the CABLE outputs but allows the MPI and serial versions to contain the same functionality.
- Changed the logic for `logn` and `wlogn` settings. `wlogn` variable is removed since all cores can use `logn` to capture their log file unit number. This allows the logs from the check ranges to appear correctly in the logs.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix

## Testing

Fluxsite tests with benchcab ran as expected showing no differences with the main branch.

Ran spatial tests with benchcab for this branch and the main branch. The netcdf files for this branch now contain outputs for all requested variables.

### Output file header for main:
```
netcdf cable_out {
dimensions:
	x = 192 ;
	y = 112 ;
	patch = 7 ;
	soil = 6 ;
	rad = 3 ;
	soil_carbon_pools = 2 ;
	plant_carbon_pools = 3 ;
	time = UNLIMITED ; // (12 currently)
	z = 1 ;
variables:
	double time(time) ;
		time:units = "seconds since 1901-01-01 00:00:00" ;
		time:coordinate = "GMT" ;
		time:calendar = "standard" ;
	float latitude(y, x) ;
		latitude:units = "degrees_north" ;
	float longitude(y, x) ;
		longitude:units = "degrees_east" ;
	float x(x) ;
		x:units = "degrees_east" ;
		x:comment = "x coordinate variable for GrADS compatibility" ;
	float y(y) ;
		y:units = "degrees_north" ;
		y:comment = "y coordinate variable for GrADS compatibility" ;
	float Area(time, y, x) ;
		Area:units = "km2" ;
		Area:long_name = "Patch Area" ;
		Area:_FillValue = -1.e+33f ;
		Area:missing_value = -1.e+33f ;

// global attributes:
		:Production = "2024/08/05 at 12:35:48" ;
		:Source = "CABLE LSM output file" ;
		:CABLE_input_file = "" ;
		:Output_averaging = "monthly" ;
}
```
### Output file header for this branch:
```
netcdf cable_out {
dimensions:
	x = 192 ;
	y = 112 ;
	patch = 7 ;
	soil = 6 ;
	rad = 3 ;
	soil_carbon_pools = 2 ;
	plant_carbon_pools = 3 ;
	time = UNLIMITED ; // (12 currently)
	z = 1 ;
variables:
	double time(time) ;
		time:units = "seconds since 1901-01-01 00:00:00" ;
		time:coordinate = "GMT" ;
		time:calendar = "standard" ;
	float latitude(y, x) ;
		latitude:units = "degrees_north" ;
	float longitude(y, x) ;
		longitude:units = "degrees_east" ;
	float x(x) ;
		x:units = "degrees_east" ;
		x:comment = "x coordinate variable for GrADS compatibility" ;
	float y(y) ;
		y:units = "degrees_north" ;
		y:comment = "y coordinate variable for GrADS compatibility" ;
	float SWdown(time, y, x) ;
		SWdown:units = "W/m^2" ;
		SWdown:long_name = "Downward shortwave radiation" ;
		SWdown:_FillValue = -1.e+33f ;
		SWdown:missing_value = -1.e+33f ;
...
```

Please add a reviewer when ready for review.

----
📚 Documentation preview 📚: https://cable--360.org.readthedocs.build/en/360/

### CODE REVIEW

**Comment by ccarouge** [comment]
@JhanSrbinovsky There was a bug in the MPI version for checking the variable ranges. To simplify the fix, I decided to remove `wlogn` which tracked the unit number for the CABLE log files on the workers. It's not needed in the offline version (can use `logn` for all cores). Can you confirm we don't use it in ESM1.5 and CM2? I've checked the code base for ESM1.5 and haven't seen it but I don't know where is the CM2 code base.

**Comment by JhanSrbinovsky** [comment]
I have never come across it online Claire. In circa AM3 models we dont even talk to the outside world - definitely not. Same in circa CM2 models, albeit less efficiently. Although there seem to be a bunch of mentions of slogan in sci and POP?

**Comment by ccarouge** [comment]
> there seem to be a bunch of mentions of slogan in sci and POP

POP declares it but doesn't use it, at least in the `main` branch. The CABLE-POP_TRENDY we'll worry about later.

SLI is using it but I now set `logn` to the value `wlogn` used to hold, so it's simply a renaming from `wlogn` to `logn` for SLI.

**Comment by ccarouge** [comment]
@Whyborn I couldn't test the changes for CASA, LUC, POP and SLI so keep an eye out for inconsistencies in there when reviewing. POP is not used from `main` so I don't worry too much about it and will be changed for CABLE4 anyway. LUC and CASA all seemed to declare the variable locally but without using it (might need a second check). For SLI, renaming wlogn to logn should work, just like for the rest of the CABLE code.

**Review by Whyborn — APPROVED** [review]
I can't see any inconsistencies, looks fine to me. Only remaining instances of ```wlogn``` are in the coupled code so not a problem for now.

**Pull request merged**
