### PR TITLE
Version of cable_nml.md for initial feedback

### PR DESCRIPTION
**Pull request by rkutteh**
# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Please include a brief summary of the change and list the issues that are fixed.
Please also include relevant motivation and context.

You can link issues by using a supported keyword in the pull request's description or in a commit message:

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [x] New or updated documentation

## Checklist

- [x] The new content is accessible and located in the appropriate section.
- [x] I have checked that links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

Please add a reviewer when ready for review.

### CODE REVIEW

**Comment by rkutteh** [comment]
I just want to know at this stage if you are happy with me including sample "input files" as MD code blocks, as in the file cable_nml.md I just pushed. The advantage of using code blocks is that of having fewer .md files. The other alternative is for me to include links inside cable_nml.md to files such as cable_nml_offline.md and cable_nml_access.md (for example). I prefer personally using inline code blocks when possible over links to other files.

**Comment by rkutteh** [comment]
@JhanSrbinovsky I am guessing that's what you are after:

https://github.com/CABLE-LSM/CABLE/blob/525b0740c3e477284e1f0e7fbcb266e13045ee67/documentation/docs/user_guide/inputs/cable_nml.md

**Comment by JhanSrbinovsky** [comment]
Thanks- that’s what I thought you were suggesting.

2 things: 1 – should we include further description of what each “thing” is even for, and 2 In the next few years cable.nml will almost certainly under go some changes. Basically split up into components. Two other namelists already exist. Another is halfway there. Related to 1), there should probably be a filename.nml for e.g. , although how relevant “filenames” will be going forward is another issue.output.nml is a better example. A separate namelist for casa.nml etc. However, having a template is a great idea. I suspect that adding other namelists alongside this one wont be an issue?

Cheers,
Jhan

From: rkutteh ***@***.***>
Date: Wednesday, 7 December 2022 at 8:20 pm
To: CABLE-LSM/CABLE ***@***.***>
Cc: Srbinovsky, Jhan (Environment, Aspendale) ***@***.***>, Mention ***@***.***>
Subject: Re: [CABLE-LSM/CABLE] Version of cable_nml.md for initial feedback (PR #88)

@JhanSrbinovsky<https://github.com/JhanSrbinovsky> I am guessing that's what you are after:

https://github.com/CABLE-LSM/CABLE/blob/525b0740c3e477284e1f0e7fbcb266e13045ee67/documentation/docs/user_guide/inputs/cable_nml.md

**Comment by rkutteh** [comment]
I think there will be no problem modifying/updating what we start with here, but it is probably simplest to put the existing templates we have now in a single MD file with code blocks, just to get things started, and in the future we can alter things as needed with further commits. I think for now we probably should hold-off on the "explanations" as they may end up in a different part of the user guide, but again it is easy to add them here later if we decide to.

**Comment by ccarouge** [comment]
I wouldn't worry about things getting split up later. The documentation needs to be a living document that will need modifications for various reasons at various stages. So let's document what we have now and update when it changes.

For the content, code blocks are great. Have you noticed how, in the documentation, it includes an icon that allows you to copy the whole block at once? https://cable-lsm.github.io/CABLE/pr-preview/pr-88/user_guide/inputs/cable_nml/ 

I think we will need more information here, there is no other place to put it but this is already a good start and can be amended later by anyone. It's always easier to modify an existing page than to start a new one.

@rkutteh I haven't yet gone through a thorough review, do you want that now or just the answer about using the code block?

**Comment by ccarouge** [comment]
I've removed Jhan and myself as reviewers for now. This way I can correctly use the notifications from GitHub once it's ready for review.

**Comment by JhanSrbinovsky** [comment]
Hey Ramzi,

I was just looking at what aspects of the user guide I was going to look at, co-incidently there was chatter about a namelist potential switch. Are you tracking them all down as part of your work? I would like to have a listing of them all. There are dozens of switches associated with the IO that are hidden, lost, unknown. 

Appendix D (and possibly others) have a lot of these but are incomplete.

https://trac.nci.org.au/trac/cable/wiki/CableUserGuide/Appendices

The problem though is not so much that the info isn't there. It's that no-one looks at it! Which is a way  bigger problem

**Comment by rkutteh** [comment]
@JhanSrbinovsky I have submitted for review a more complete version of the previous cable_nml.md. I will start rounding up all of the namelist variables I can find and include in future commits. Thanks for the link. I am doing some of the input files for the rest of the day...

**Pull request merged**
