### PR TITLE
Point API link to Ford docs directly

### PR DESCRIPTION
**Pull request by SeanBryan51**
The `api.md` page (currently https://cable.readthedocs.io/en/latest/developer_guide/other_resources/api/) does not contain any useful information. This change points the API link under Developer Guide to the Ford documentation directly and removes `api.md`.

## Type of change

- [x] New or updated documentation

## Checklist

- [x] The new content is accessible and located in the appropriate section.
- [x] I have checked that links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

----
📚 Documentation preview 📚: https://cable--442.org.readthedocs.build/en/442/

### CODE REVIEW

**Comment by SeanBryan51** [comment]
I have grepped the source code for `api.md` and didn't find any occurrences. The file is safe to remove.

**Review by bschroeter — CHANGES_REQUESTED** [review]
While this is fine for this instance, I think it would be better to make the link to API docs more prominent in the documentation. i.e. instead of getting to a secondary (or even tertiary) menu item, there should be an "API Reference" link in the main menu (across the top) that goes straight to the FORD documentation. Extra points if you can get it to open in a new window.

https://stackoverflow.com/questions/4425198/can-i-create-links-with-target-blank-in-markdown

Not sure what mkdocs is using for Markdown parsing, so the kramdown syntax may not work.

**Comment by SeanBryan51** [comment]
@ccarouge I decided not to remove `src/offline/CSIRO_BSD_MIT_License_v2.0_CABLE.txt` as it is referenced in a lot of existing source files (see [this search](https://github.com/search?q=repo%3ACABLE-LSM%2FCABLE%20CSIRO_BSD_MIT_License_v2.0_CABLE.txt&type=code)).

**Comment by SeanBryan51** [comment]
@bschroeter I wasn't able to get a new window to open but I have now added API Reference to the main page

**Review by bschroeter — APPROVED** [review]
A thing of beauty, approved.

**Pull request merged**
