### PR TITLE
exterminate cable_data

### LINKED ISSUE #448: remove cable_data and instance USEing it
instances USEing cable_data:
`
coupled/ESM1.5/casa_um_inout.F90:                                  USE cable_data_module, ONLY : MATH
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90:                  USE cable_data_module, ONLY : icbm_type, point2constants
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_explicit_driver.F90:  USE cable_data_module, ONLY : PHYS
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_hyd_driver.F90:        USE cable_data_module, ONLY : PHYS, OTHER
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_implicit_driver.F90:  USE cable_data_module, ONLY : PHYS
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_implicit_driver.F90:  USE cable_data_module, ONLY : PHYS
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init_subrs.F90:  USE cable_data_module, ONLY : PHYS, OTHER
coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init_subrs.F90:  USE cable_data_module, ONLY : PHYS
`

### PR DESCRIPTION
**Pull request by JhanSrbinovsky**
# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Get rid of cable_data from ESM1.5 model

Fixes #448

## Type of change

Please delete options that are not relevant.

Remove redundant code

## Checklist

- [x] The new content is accessible and located in the appropriate section.
- [x] I have checked that links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

Rachel, can you please test this in your ESM1.5 setup. Mine is not at hand. It won't affect offline.

----
📚 Documentation preview 📚: https://cable--450.org.readthedocs.build/en/450/

### CODE REVIEW

**Review by rml599gh — COMMENTED** [review]
In cable_cbm.F90 can line 40-41 be removed since we will no longer be using 'C'?

In cable_explicit_driver.F90 - does the new line 91-93 (making CAPP) available need to be here or should it be in the cable_expl_unpack subroutine as that seems to be where it is used?

In cable_implicit_driver.F90: USE cable_phys_constants_mod, only: TFRZ has been added in both the cable_implict_driver subroutine and the implicit_unpack subroutine. As far as I can see tfrz is only used in implicit_unpack, so does the USE statement need to be in both subroutines?

In cable_um_init_subrs.F90:
Is TFRZ used in subroutine initialize_radiation? If not, then presumably don't need line 494.
Also in subrouting initialize_soilsnow, I can't see where TFRZ is used so perhaps line 642 is not needed.

Aside from these code queries, can you report on some testing to show impact (hopefully none) of the changes.

**Comment by JhanSrbinovsky** [comment]
code changes all made. I'll have to setup an ESM1.5 build/run w the current main CABLE and then a 2nd with this branch

**Comment by JhanSrbinovsky** [comment]
ESM1.5+CABLE3, the one with CABLE:main branch in place,  Comparing main@HEAD  with #448 show global Temp fields after one year to be identical.
Screenshot 2024-11-18 at 3 47 05 pm

**Comment by JhanSrbinovsky** [comment]
oddly - I did the ESM1.5 set first. My expectation was that there is no way offline is going to be impacted. For thoroughness I did the offline benchcab thing, ALL regression tests failed. Then I thought to re-base #448, and it worked. The suggestion being that something in offline/ changed in the interim.

**Comment by JhanSrbinovsky** [comment]
@ccarouge - can you look at this please, it looks like problem is  on within action end, local build works fine. here it doesnt even get that far

**Review by rml599gh — APPROVED** [review]

**Comment by JhanSrbinovsky** [comment]
remove met%tk issue was merged earlier today - after the automatic build fail. Since resolved, but the auto-build test fails. @ccarouge, this builds with build.bash and benchcab. something is going on with action here, nonetheless I dont want to merge until is worked out

**Comment by JhanSrbinovsky** [comment]
@ccarouge IDK what changed but it worked after being re-run. No changes on code side.

**Pull request merged**
